add status condtional

diff --git a/.github/workflows/main.yaml b/.github/workflows/main.yaml
--- a/.github/workflows/main.yaml
+++ b/.github/workflows/main.yaml
@@ -63,3 +63,19 @@ jobs:
             --query "Command.CommandId")
 
           echo "Command ID: $command_id"
+
+          aws ssm wait command-executed \
+            --command-id $command_id \
+            --instance-id $INSTANCE_IDS[0] \
+
+          status = $(aws ssm list-commands \
+            --command-id $command_id \
+            --instance-id $INSTANCE_IDS[0] \
+            --query "Commands[0].Status" \
+            --output text)
+
+          echo "Command execution status: $status"
+          if [ "$status" != "Success" ]; then
+            echo "Command failed with status: $status"
+            exit 1
+          fi
